spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/groundandgrow_dev

logging:
  level:
    com.groundandgrow: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true
